### ISSUE TITLE
пиво нельзя выпить, а рис нельзя съесть

### ISSUE THREAD

**Issue by eqozqq** [MineDg2665/WorldPEClient#1]
неужели создателю клиента так сложно это реализовать? у него ведь имеется исходный код мкпе.

**Comment by mryoshiii** [comment]
> у него ведь имеется исходный код мкпе.

К сожалению после таких действий к дому MineDG приедет ФСБ и после чего ебнут ;3

**Comment by MineDg2665** [comment]
Иди наху всё работает
