### ISSUE TITLE
Открыть исходный код Minecraft : Pocket Edition 0.8.1

### ISSUE THREAD

**Issue by mryoshiii** [MineDg2665/WorldPEClient#2]
Учитывая что на данный момент мы имеем только ОРИГИНАЛЬНЫЙ и ЛУЧШИЙ клиент то почему мы не можем глянуть его исходный код? 😥 Прошу , откройте исходный код для Minecraft : Pocket Edition.

**Comment by MineDg2665** [comment]
.
